name: CI
on:
  push:
    branches: [ master, ci-cd ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: android-actions/setup-android@v2.0.2

      - name: Build
        run: ./gradlew assembleRelease

      - name: UnitTest
        run: ./gradlew test
