name: Android Upload Apk CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  apk:
    name: Apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Gradle Android
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/release/app-release.apk
